# Pinned base image for reproducibility
FROM python:3.10.14-slim

WORKDIR /app

# Create non-root user for security
RUN useradd -m -u 1000 appuser

# Install dependencies first (layer caching)
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Copy application code and config
COPY src/ src/
COPY configs/ configs/

# Copy pre-built artifacts (pipeline + model)
# These are generated by the DVC pipeline before Docker build
COPY data/processed/pipeline.pkl data/processed/pipeline.pkl
COPY models/best_model.pkl models/best_model.pkl

RUN chown -R appuser:appuser /app
USER appuser

EXPOSE 8000

HEALTHCHECK --interval=30s --timeout=10s --start-period=10s --retries=3 \
  CMD python -c "import urllib.request; urllib.request.urlopen('http://localhost:8000/health')"

CMD ["uvicorn", "src.serving.app:app", "--host", "0.0.0.0", "--port", "8000"]
